<a href="https://colab.research.google.com/github/AbuObaida01/EssentialMathsForML/blob/main/EssentialMathsForML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lecture 01: Vectors in Machine Learning

In [1]:
import numpy as np
w=np.array([1,2,3])
x=np.array([5,6,7])

In [2]:
print(w+x)

[ 6  8 10]


In [3]:
print(w-x)

[-4 -4 -4]


In [4]:
print(5*w)

[ 5 10 15]


In [5]:
# To find the length of the array
# len=((x1^2+x2^2+...+xn^2))root
print(np.linalg.norm(x))

10.488088481701515


In [6]:
print(np.dot(w,x))

38


## Lecture 02 : Basics of Matrix Algebra


In [7]:
p=np.array([[1,1],[5,-1],[3,2]])
print(p)

[[ 1  1]
 [ 5 -1]
 [ 3  2]]


In [8]:
q=np.array([[1,0],[6,-4],[3,8]])
print(q)

[[ 1  0]
 [ 6 -4]
 [ 3  8]]


In [10]:
r=np.add(p,q)
print(r)

[[ 2  1]
 [11 -5]
 [ 6 10]]


In [11]:
s=np.subtract(p,q)
print(s)

[[ 0  1]
 [-1  3]
 [ 0 -6]]


In [13]:
t=np.array([[1,3,5,7],[8,4,9,10]])
print(t)

[[ 1  3  5  7]
 [ 8  4  9 10]]


In [14]:
u=np.dot(p,t)
print(u)

[[ 9  7 14 17]
 [-3 11 16 25]
 [19 17 33 41]]


In [16]:
w=np.array([[1,0,5],[6,-4,9],[3,8,8]])
print(w)

[[ 1  0  5]
 [ 6 -4  9]
 [ 3  8  8]]


In [17]:
det=np.linalg.det(w)
print(w)

[[ 1  0  5]
 [ 6 -4  9]
 [ 3  8  8]]
