<a href="https://colab.research.google.com/github/AbuObaida01/EssentialMathsForML/blob/main/EssentialMathsForML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lecture 01: Vectors in Machine Learning

In [ ]:
import numpy as np
w=np.array([1,2,3])
x=np.array([5,6,7])

In [ ]:
print(w+x)

[ 6  8 10]


In [ ]:
print(w-x)

[-4 -4 -4]


In [ ]:
print(5*w)

[ 5 10 15]


In [ ]:
# To find the length of the array
# len=((x1^2+x2^2+...+xn^2))root
print(np.linalg.norm(x))

10.488088481701515


In [ ]:
print(np.dot(w,x))

38
